//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Substrate.Shibuya.NET.RestClient.Mockup
{
   using System;
   using System.Threading.Tasks;
   using System.Net.Http;
   using Substrate.Shibuya.NET.RestClient.Mockup.Generated.Interfaces;
   using Substrate.Shibuya.NET.RestClient.Mockup.Generated.Clients;
   
   public sealed class MockupClient
   {
      private HttpClient _httpClient;
      public IAssetsControllerMockupClient AssetsControllerClient;
      public IAuraControllerMockupClient AuraControllerClient;
      public IAuraExtControllerMockupClient AuraExtControllerClient;
      public IAuthorshipControllerMockupClient AuthorshipControllerClient;
      public IBalancesControllerMockupClient BalancesControllerClient;
      public IBaseFeeControllerMockupClient BaseFeeControllerClient;
      public IBlockRewardControllerMockupClient BlockRewardControllerClient;
      public ICollatorSelectionControllerMockupClient CollatorSelectionControllerClient;
      public IContractsControllerMockupClient ContractsControllerClient;
      public ICouncilControllerMockupClient CouncilControllerClient;
      public IDappsStakingControllerMockupClient DappsStakingControllerClient;
      public IDemocracyControllerMockupClient DemocracyControllerClient;
      public IDmpQueueControllerMockupClient DmpQueueControllerClient;
      public IEthereumControllerMockupClient EthereumControllerClient;
      public IEVMChainIdControllerMockupClient EVMChainIdControllerClient;
      public IEVMControllerMockupClient EVMControllerClient;
      public IIdentityControllerMockupClient IdentityControllerClient;
      public IMultisigControllerMockupClient MultisigControllerClient;
      public IParachainInfoControllerMockupClient ParachainInfoControllerClient;
      public IParachainSystemControllerMockupClient ParachainSystemControllerClient;
      public IPolkadotXcmControllerMockupClient PolkadotXcmControllerClient;
      public IPreimageControllerMockupClient PreimageControllerClient;
      public IProxyControllerMockupClient ProxyControllerClient;
      public IRandomnessCollectiveFlipControllerMockupClient RandomnessCollectiveFlipControllerClient;
      public ISchedulerControllerMockupClient SchedulerControllerClient;
      public ISessionControllerMockupClient SessionControllerClient;
      public IStateTrieMigrationControllerMockupClient StateTrieMigrationControllerClient;
      public ISudoControllerMockupClient SudoControllerClient;
      public ISystemControllerMockupClient SystemControllerClient;
      public ITechnicalCommitteeControllerMockupClient TechnicalCommitteeControllerClient;
      public ITimestampControllerMockupClient TimestampControllerClient;
      public ITransactionPaymentControllerMockupClient TransactionPaymentControllerClient;
      public ITreasuryControllerMockupClient TreasuryControllerClient;
      public IVestingControllerMockupClient VestingControllerClient;
      public IXcAssetConfigControllerMockupClient XcAssetConfigControllerClient;
      public IXcmpQueueControllerMockupClient XcmpQueueControllerClient;
      public MockupClient(HttpClient httpClient)
      {
         _httpClient = httpClient;
         AssetsControllerClient = new AssetsControllerMockupClient(_httpClient);
         AuraControllerClient = new AuraControllerMockupClient(_httpClient);
         AuraExtControllerClient = new AuraExtControllerMockupClient(_httpClient);
         AuthorshipControllerClient = new AuthorshipControllerMockupClient(_httpClient);
         BalancesControllerClient = new BalancesControllerMockupClient(_httpClient);
         BaseFeeControllerClient = new BaseFeeControllerMockupClient(_httpClient);
         BlockRewardControllerClient = new BlockRewardControllerMockupClient(_httpClient);
         CollatorSelectionControllerClient = new CollatorSelectionControllerMockupClient(_httpClient);
         ContractsControllerClient = new ContractsControllerMockupClient(_httpClient);
         CouncilControllerClient = new CouncilControllerMockupClient(_httpClient);
         DappsStakingControllerClient = new DappsStakingControllerMockupClient(_httpClient);
         DemocracyControllerClient = new DemocracyControllerMockupClient(_httpClient);
         DmpQueueControllerClient = new DmpQueueControllerMockupClient(_httpClient);
         EthereumControllerClient = new EthereumControllerMockupClient(_httpClient);
         EVMChainIdControllerClient = new EVMChainIdControllerMockupClient(_httpClient);
         EVMControllerClient = new EVMControllerMockupClient(_httpClient);
         IdentityControllerClient = new IdentityControllerMockupClient(_httpClient);
         MultisigControllerClient = new MultisigControllerMockupClient(_httpClient);
         ParachainInfoControllerClient = new ParachainInfoControllerMockupClient(_httpClient);
         ParachainSystemControllerClient = new ParachainSystemControllerMockupClient(_httpClient);
         PolkadotXcmControllerClient = new PolkadotXcmControllerMockupClient(_httpClient);
         PreimageControllerClient = new PreimageControllerMockupClient(_httpClient);
         ProxyControllerClient = new ProxyControllerMockupClient(_httpClient);
         RandomnessCollectiveFlipControllerClient = new RandomnessCollectiveFlipControllerMockupClient(_httpClient);
         SchedulerControllerClient = new SchedulerControllerMockupClient(_httpClient);
         SessionControllerClient = new SessionControllerMockupClient(_httpClient);
         StateTrieMigrationControllerClient = new StateTrieMigrationControllerMockupClient(_httpClient);
         SudoControllerClient = new SudoControllerMockupClient(_httpClient);
         SystemControllerClient = new SystemControllerMockupClient(_httpClient);
         TechnicalCommitteeControllerClient = new TechnicalCommitteeControllerMockupClient(_httpClient);
         TimestampControllerClient = new TimestampControllerMockupClient(_httpClient);
         TransactionPaymentControllerClient = new TransactionPaymentControllerMockupClient(_httpClient);
         TreasuryControllerClient = new TreasuryControllerMockupClient(_httpClient);
         VestingControllerClient = new VestingControllerMockupClient(_httpClient);
         XcAssetConfigControllerClient = new XcAssetConfigControllerMockupClient(_httpClient);
         XcmpQueueControllerClient = new XcmpQueueControllerMockupClient(_httpClient);
      }
   }
}
